WIP more encapsulation for classifications parsing logic

diff --git a/bin/pre-commit b/bin/pre-commit
--- a/bin/pre-commit
+++ b/bin/pre-commit
@@ -7,3 +7,11 @@ if [[ "$RC" != "0" ]]; then
   echo "(pylint failed. [code $RC])"
   exit $RC
 fi
+
+python3 -m pytest
+RC=$?
+
+if [[ "$RC" != "0" ]]; then
+  echo "(pytest failed. [code $RC])"
+  exit $RC
+fi
